### ISSUE TITLE
Avoid out and ref

### ISSUE THREAD

**Issue by huntipl** [JuliuszMaretzky/Seed#2]
https://github.com/JuliuszMaretzky/Seed/blob/30eba22284f4aec56a8a964be8cb32434033ed4a/Seed/Service.cs#L20

Return things, structs, but avoid out and ref.

https://stackoverflow.com/questions/3539252/when-is-using-the-c-sharp-ref-keyword-ever-a-good-idea

**Comment by JuliuszMaretzky** [comment]
In this single case I think it is not a bad idea.

**Comment by huntipl** [comment]
people always say that. I would replace it with struct and return it and pass it along to other places.
Always avoid out and ref :)

**Comment by JuliuszMaretzky** [comment]
As you wish, Boss ;-)
